### PR TITLE
Change InvalidArgumentException to IllegalArgumentException

### PR DESCRIPTION
**Pull request by WestonReed**
IllegalArgumentException does not require any imports, and should be used instead of InvalidArgumentException.

See: https://stackoverflow.com/a/7334226/7432811

### CODE REVIEW

**Comment by Phytolizer** [comment]
Oops, forgot that existed.

**Comment by Phytolizer** [comment]
That merged your netbeans files too. I'll fix it once I'm done working on my ISP.

**Comment by WestonReed** [comment]
Would you like me to add this .gitignore?

https://github.com/WestonReed/CSGameClient/blob/master/.gitignore

**Comment by Phytolizer** [comment]
Yes, that'd be helpful.

**Pull request merged**
